apiVersion: v1
kind: Pod
metadata:
  name: devops-workshop
spec:
  securityContext:
    fsGroup: 1000
  initContainers:
    - name: init-chown-jenkins
      image: busybox
      command: ["sh", "-c", "chown -R 1000:1000 /var/jenkins_home || true"]
      volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
  containers:
    - name: jenkins
      image: jenkins/jenkins:lts
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home

    - name: maven
      image: maven:3.9.9-eclipse-temurin-17
      command: ["cat"]
      tty: true

    - name: docker
      image: docker:24-dind
      securityContext:
        privileged: true
      command: ["dockerd-entrypoint.sh"]
      args: []

  volumes:
    - name: jenkins-home
      hostPath:
        path: /var/jenkins_home
        type: DirectoryOrCreate
